server:
  port: ${PORT:8888}
---
logging:
  level:
    com.netflix.discovery: 'OFF'
---
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ordineo/config.git
---
spring:
  profiles: cloud
server:
  port: ${PORT}
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
    nonSecurePortEnabled: false
    securePortEnabled: true
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: ${vcap.services.registry.credentials.url}
    healthcheck:
      enabled: true
